name: CI/CD Pipeline
run-name: ${{ github.actor }} is testing the soccer app 🚀

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    
    - name: Build application
      run: npm run build
    
