name: CI/CD Pipeline
run-name: ${{ github.actor }} is testing the soccer app 🚀

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a message
        run: echo "Hello! This is a push event."

